In [18]:
print(df.shape)
print(df["stock_code"].nunique())
print(df["stock_code"].value_counts().head())
print(df[["stock_code", "trade_date", "target_return_5d"]].head())

(2685, 28)
5
stock_code
660      537
5380     537
5930     537
35420    537
35720    537
Name: count, dtype: int64
   stock_code  trade_date  target_return_5d
0         660  2024-06-11          0.103529
1         660  2024-06-12          0.086047
2         660  2024-06-13          0.069820
3         660  2024-06-14          0.058824
4         660  2024-06-17          0.000000

In [19]:
print(df.dtypes)
print(df.isnull().sum().sum())

stock_code            int64
trade_date              str
return_1d           float64
return_5d           float64
return_10d          float64
return_20d          float64
intraday_return     float64
high_low_range      float64
gap                 float64
sma_5               float64
sma_20              float64
sma_60              float64
price_to_sma_5      float64
price_to_sma_20     float64
price_to_sma_60     float64
rsi_14              float64
roc_10              float64
roc_20              float64
macd                float64
macd_signal         float64
macd_hist           float64
volatility_5        float64
volatility_20       float64
atr_14              float64
volume_change_1d    float64
volume_sma_20       float64
volume_ratio_20     float64
target_return_5d    float64
dtype: object
0

In [20]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd

from src.feature_selection.mutual_information import (
    calculate_mutual_information,
    calculate_feature_mutual_information,
)

In [21]:
DATA_PATH = PROJECT_ROOT / "data" / "processed" / "ml_dataset.csv"

df = pd.read_csv(DATA_PATH)

df.shape

(2685, 28)

In [22]:
TARGET = "target_return_5d"
ID_COLUMNS = ["stock_code", "trade_date"]

FEATURE_COLUMNS = [
    col for col in df.columns
    if col not in ID_COLUMNS + [TARGET]
]

X = df[FEATURE_COLUMNS].copy()
y = df[TARGET].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Number of features:", len(FEATURE_COLUMNS))

X shape: (2685, 25)
y shape: (2685,)
Number of features: 25

In [23]:
mi_scores = calculate_mutual_information(
    X,
    y,
    random_state=42,
)

mi_scores

sma_5               0.092133
sma_20              0.075937
atr_14              0.073692
sma_60              0.070101
volatility_20       0.068883
volume_sma_20       0.066023
price_to_sma_60     0.056106
rsi_14              0.053273
macd                0.051430
price_to_sma_20     0.044671
volatility_5        0.040760
roc_20              0.039974
return_20d          0.039965
macd_signal         0.033943
gap                 0.033707
macd_hist           0.031132
return_1d           0.026349
volume_change_1d    0.022044
roc_10              0.016100
return_10d          0.016059
high_low_range      0.014721
price_to_sma_5      0.013704
return_5d           0.013152
volume_ratio_20     0.006572
intraday_return     0.000000
Name: mutual_information, dtype: float64

In [24]:
mi_results = mi_scores.reset_index()
mi_results.columns = ["feature", "mi_score"]

mi_results

             feature  mi_score
0              sma_5  0.092133
1             sma_20  0.075937
2             atr_14  0.073692
3             sma_60  0.070101
4      volatility_20  0.068883
5      volume_sma_20  0.066023
6    price_to_sma_60  0.056106
7             rsi_14  0.053273
8               macd  0.051430
9    price_to_sma_20  0.044671
10      volatility_5  0.040760
11            roc_20  0.039974
12        return_20d  0.039965
13       macd_signal  0.033943
14               gap  0.033707
15         macd_hist  0.031132
16         return_1d  0.026349
17  volume_change_1d  0.022044
18            roc_10  0.016100
19        return_10d  0.016059
20    high_low_range  0.014721
21    price_to_sma_5  0.013704
22         return_5d  0.013152
23   volume_ratio_20  0.006572
24   intraday_return  0.000000

In [25]:
import pandas as pd

DATA_PATH = PROJECT_ROOT / "data" / "processed" / "ml_dataset.csv"

df = pd.read_csv(DATA_PATH)

TARGET = "target_return_5d"
ID_COLUMNS = ["stock_code", "trade_date"]

FEATURE_COLUMNS = [
    col for col in df.columns
    if col not in ID_COLUMNS + [TARGET]
]

X = df[FEATURE_COLUMNS].copy()
y = df[TARGET].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2685, 25)
y shape: (2685,)

In [4]:
mi_matrix = calculate_feature_mutual_information(
    X,
    random_state=42,
)

mi_matrix

,return_1d,return_5d,return_10d,return_20d,intraday_return,high_low_range,gap,sma_5,sma_20,sma_60,...,roc_20,macd,macd_signal,macd_hist,volatility_5,volatility_20,atr_14,volume_change_1d,volume_sma_20,volume_ratio_20
return_1d,0.000000,0.139045,0.072892,0.064534,0.590836,0.201050,0.272274,0.267512,0.168916,0.086628,...,0.064534,0.047641,0.047901,0.024838,0.180285,0.116514,0.086687,0.083187,0.087893,0.115599
return_5d,0.139045,0.000000,0.368003,0.201841,0.063755,0.078634,0.103450,0.100724,0.084446,0.091127,...,0.201841,0.129589,0.077677,0.302843,0.174976,0.121862,0.102379,0.000000,0.094834,0.113060
return_10d,0.072892,0.368003,0.000000,0.436106,0.079212,0.129943,0.067880,0.153295,0.144588,0.185081,...,0.436106,0.291461,0.172214,0.613728,0.115350,0.222376,0.195440,0.000000,0.155978,0.060745
return_20d,0.064534,0.201841,0.436106,0.000000,0.038361,0.075104,0.052645,0.277313,0.246194,0.294757,...,6.630282,0.715967,0.481400,0.286162,0.161803,0.347585,0.289020,0.000000,0.278970,0.051378
intraday_return,0.590836,0.063755,0.079212,0.038361,0.000000,0.530469,0.052903,0.274167,0.164524,0.112762,...,0.037755,0.029036,0.022327,0.040020,0.110814,0.061211,0.095628,0.034579,0.061496,0.108304
high_low_range,0.201050,0.078634,0.129943,0.075104,0.530469,0.000000,0.047822,0.249082,0.186584,0.167677,...,0.075170,0.118365,0.135708,0.118546,0.231536,0.184935,0.212645,0.039712,0.142970,0.119285
gap,0.272274,0.103450,0.067880,0.052645,0.052903,0.047822,0.000000,0.503419,0.315688,0.244846,...,0.052528,0.112968,0.124725,0.077724,0.121513,0.135513,0.217495,0.030879,0.130804,0.044841
sma_5,0.267512,0.100724,0.153295,0.277313,0.274167,0.249082,0.503419,0.000000,2.685291,2.515129,...,0.277122,1.286259,1.338387,0.683408,0.296598,0.915418,1.806561,0.000000,1.332433,0.032459
sma_20,0.168916,0.084446,0.144588,0.246194,0.164524,0.186584,0.315688,2.685291,0.000000,2.991409,...,0.245942,1.130010,1.359178,0.740814,0.292157,0.986287,2.034364,0.005130,1.490580,0.031005
sma_60,0.086628,0.091127,0.185081,0.294757,0.112762,0.167677,0.244846,2.515129,2.991409,0.000000,...,0.294654,1.251052,1.427638,0.749761,0.287445,1.013171,2.118494,0.004115,1.611248,0.028117
price_to_sma_5,0.434421,0.584129,0.230360,0.161300,0.243388,0.153846,0.193392,0.047050,0.074875,0.061438,...,0.161299,0.065214,0.080860,0.144983,0.131164,0.119018,0.085863,0.015451,0.068572,0.126766
price_to_sma_20,0.103278,0.463304,0.995035,0.757523,0.117834,0.152956,0.052991,0.182654,0.176142,0.225592,...,0.757455,0.411652,0.248735,0.576216,0.159651,0.230057,0.219038,0.000000,0.173240,0.074293
price_to_sma_60,0.044365,0.195606,0.340588,0.760909,0.047795,0.094160,0.049240,0.512822,0.447230,0.475409,...,0.760897,1.106892,0.919784,0.262956,0.180526,0.404690,0.381224,0.000000,0.373228,0.042542
rsi_14,0.061682,0.363171,0.595890,0.747241,0.040827,0.044856,0.029895,0.207904,0.180920,0.240785,...,0.747201,0.552010,0.332743,0.327680,0.057566,0.120626,0.113924,0.032309,0.164776,0.100702
roc_10,0.072892,0.368003,6.622520,0.436335,0.078906,0.129783,0.067849,0.153324,0.144706,0.185213,...,0.436106,0.291461,0.172214,0.613728,0.115350,0.222376,0.195440,0.000000,0.155978,0.060745
roc_20,0.064534,0.201841,0.436106,6.630282,0.037755,0.075170,0.052528,0.277122,0.245942,0.294654,...,0.000000,0.715967,0.481400,0.286162,0.161803,0.347585,0.289020,0.000000,0.278970,0.051378
macd,0.047641,0.129589,0.291461,0.715967,0.029036,0.118365,0.112968,1.286259,1.130010,1.251052,...,0.715967,0.000000,1.592145,0.500444,0.248246,0.622684,1.000976,0.000000,0.725590,0.034895
macd_signal,0.047901,0.077677,0.172214,0.481400,0.022327,0.135708,0.124725,1.338387,1.359178,1.427638,...,0.481400,1.592145,0.000000,0.434250,0.224640,0.704984,1.103025,0.000000,0.899116,0.017520
macd_hist,0.024838,0.302843,0.613728,0.286162,0.040020,0.118546,0.077724,0.683408,0.740814,0.749761,...,0.286162,0.500444,0.434250,0.000000,0.214919,0.469333,0.718858,0.014353,0.370514,0.070765
volatility_5,0.180285,0.174976,0.115350,0.161803,0.110814,0.231536,0.121513,0.296598,0.292157,0.287445,...,0.161803,0.248246,0.224640,0.214919,0.000000,0.502106,0.367748,0.016693,0.288691,0.049917
volatility_20,0.116514,0.121862,0.222376,0.347585,0.061211,0.184935,0.135513,0.915418,0.986287,1.013171,...,0.347585,0.622684,0.704984,0.469333,0.502106,0.000000,1.004180,0.000000,0.909045,0.006191
atr_14,0.086687,0.102379,0.195440,0.289020,0.095628,0.212645,0.217495,1.806561,2.034364,2.118494,...,0.289020,1.000976,1.103025,0.718858,0.367748,1.004180,0.000000,0.012363,1.257535,0.017756
volume_change_1d,0.083187,0.000000,0.000000,0.000000,0.034579,0.039712,0.030879,0.000000,0.005130,0.004115,...,0.000000,0.000000,0.000000,0.014353,0.016693,0.000000,0.012363,0.000000,0.018240,0.194927
volume_sma_20,0.087893,0.094834,0.155978,0.278970,0.061496,0.142970,0.130804,1.332433,1.490580,1.611248,...,0.278970,0.725590,0.899116,0.370514,0.288691,0.909045,1.257535,0.018240,0.000000,0.025694
volume_ratio_20,0.115599,0.113060,0.060745,0.051378,0.108304,0.119285,0.044841,0.032459,0.031005,0.028117,...,0.051378,0.034895,0.017520,0.070765,0.049917,0.006191,0.017756,0.194927,0.025694,0.000000

In [5]:
import numpy as np


def calculate_mrmr_scores(
    relevance: pd.Series,
    redundancy: pd.DataFrame,
    selected_features: list[str],
) -> pd.Series:
    """
    Calculate MRMR scores for candidate features.

    MRMR = relevance - average redundancy
    """
    scores = {}

    for feature in relevance.index:
        if feature in selected_features:
            continue

        if len(selected_features) == 0:
            avg_redundancy = 0.0
        else:
            avg_redundancy = redundancy.loc[
                feature, selected_features
            ].mean()

        scores[feature] = relevance[feature] - avg_redundancy

    return pd.Series(scores).sort_values(ascending=False)

In [14]:
mi_matrix.to_csv("../data/processed/filter_results/feature_mi_matrix.csv")

In [26]:
mi_results.to_csv(
    "../data/processed/filter_results/feature_target_mi.csv",
    index=False,
)