In [2]:
import pandas as pd
import numpy as np
from scipy.stats import f_oneway

In [7]:
df = pd.read_csv("../data/processed/ml_dataset.csv")

print(df.shape)
print(df.columns.tolist())

(2685, 28)
['stock_code', 'trade_date', 'return_1d', 'return_5d', 'return_10d', 'return_20d', 'intraday_return', 'high_low_range', 'gap', 'sma_5', 'sma_20', 'sma_60', 'price_to_sma_5', 'price_to_sma_20', 'price_to_sma_60', 'rsi_14', 'roc_10', 'roc_20', 'macd', 'macd_signal', 'macd_hist', 'volatility_5', 'volatility_20', 'atr_14', 'volume_change_1d', 'volume_sma_20', 'volume_ratio_20', 'target_return_5d']

In [8]:
df.head()

,stock_code,trade_date,return_1d,return_5d,return_10d,return_20d,intraday_return,high_low_range,gap,sma_5,...,macd,macd_signal,macd_hist,volatility_5,volatility_20,atr_14,volume_change_1d,volume_sma_20,volume_ratio_20,target_return_5d
0,660,2024-06-11,0.021635,0.094233,0.054591,0.181212,0.011905,0.043689,0.009615,203000.0,...,6187.902397,5195.016563,992.885834,0.031048,0.023996,6757.468051,0.253659,3435519.80,0.893653,0.103529
1,660,2024-06-12,0.011765,0.112261,0.061728,0.169750,0.014151,0.023697,-0.002353,207340.0,...,6911.664995,5538.346249,1373.318746,0.028770,0.023814,6631.934619,-0.299278,3381585.20,0.636190,0.086047
2,660,2024-06-13,0.032558,0.146102,0.096296,0.198057,-0.017699,0.034247,0.051163,213000.0,...,7958.354609,6022.347921,1936.006687,0.026692,0.024432,6979.653575,1.685444,3532295.70,1.635559,0.069820
3,660,2024-06-14,-0.004505,0.065060,0.129280,0.145078,-0.017778,0.041667,0.013514,215700.0,...,8607.944994,6539.467336,2068.477659,0.014806,0.023386,7123.964034,-0.426854,3443697.95,0.961531,0.058824
4,660,2024-06-17,0.009050,0.072115,0.178647,0.174302,0.018265,0.047945,-0.009050,218700.0,...,9178.331251,7067.240119,2111.091132,0.013915,0.022745,7365.109460,-0.336094,3411545.25,0.644382,0.000000

In [9]:
df.columns.tolist()

['stock_code',
 'trade_date',
 'return_1d',
 'return_5d',
 'return_10d',
 'return_20d',
 'intraday_return',
 'high_low_range',
 'gap',
 'sma_5',
 'sma_20',
 'sma_60',
 'price_to_sma_5',
 'price_to_sma_20',
 'price_to_sma_60',
 'rsi_14',
 'roc_10',
 'roc_20',
 'macd',
 'macd_signal',
 'macd_hist',
 'volatility_5',
 'volatility_20',
 'atr_14',
 'volume_change_1d',
 'volume_sma_20',
 'volume_ratio_20',
 'target_return_5d']

In [10]:
target_col = "target_return_5d"

X = df.drop(columns=[target_col])
y = df[target_col]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2685, 27)
y shape: (2685,)

In [11]:
# feature별 고유값 개수 확인
feature_info = pd.DataFrame({
    "feature": X.columns,
    "unique_count": X.nunique(),
    "missing_count": X.isna().sum()
})

feature_info

                           feature  unique_count  missing_count
stock_code              stock_code             5              0
trade_date              trade_date           537              0
return_1d                return_1d          2439              0
return_5d                return_5d          2537              0
return_10d              return_10d          2605              0
return_20d              return_20d          2611              0
intraday_return    intraday_return          2393              0
high_low_range      high_low_range          2325              0
gap                            gap          2245              0
sma_5                        sma_5          2170              0
sma_20                      sma_20          2556              0
sma_60                      sma_60          2635              0
price_to_sma_5      price_to_sma_5          2615              0
price_to_sma_20    price_to_sma_20          2675              0
price_to_sma_60    price_to_sma_60          2683              0
rsi_14                      rsi_14          2609              0
roc_10                      roc_10          2605              0
roc_20                      roc_20          2611              0
macd                          macd          2685              0
macd_signal            macd_signal          2685              0
macd_hist                macd_hist          2685              0
volatility_5          volatility_5          2684              0
volatility_20        volatility_20          2679              0
atr_14                      atr_14          2685              0
volume_change_1d  volume_change_1d          2685              0
volume_sma_20        volume_sma_20          2685              0
volume_ratio_20    volume_ratio_20          2685              0

In [12]:
X.dtypes

stock_code            int64
trade_date              str
return_1d           float64
return_5d           float64
return_10d          float64
return_20d          float64
intraday_return     float64
high_low_range      float64
gap                 float64
sma_5               float64
sma_20              float64
sma_60              float64
price_to_sma_5      float64
price_to_sma_20     float64
price_to_sma_60     float64
rsi_14              float64
roc_10              float64
roc_20              float64
macd                float64
macd_signal         float64
macd_hist           float64
volatility_5        float64
volatility_20       float64
atr_14              float64
volume_change_1d    float64
volume_sma_20       float64
volume_ratio_20     float64
dtype: object

In [13]:
feature_cols = [
    col for col in df.columns
    if col not in ["stock_code", "trade_date", "target_return_5d"]
]

X = df[feature_cols]
y = df["target_return_5d"]

print("Feature 개수:", len(feature_cols))
print("Feature:", feature_cols)
print("X shape:", X.shape)
print("y shape:", y.shape)

Feature 개수: 25
Feature: ['return_1d', 'return_5d', 'return_10d', 'return_20d', 'intraday_return', 'high_low_range', 'gap', 'sma_5', 'sma_20', 'sma_60', 'price_to_sma_5', 'price_to_sma_20', 'price_to_sma_60', 'rsi_14', 'roc_10', 'roc_20', 'macd', 'macd_signal', 'macd_hist', 'volatility_5', 'volatility_20', 'atr_14', 'volume_change_1d', 'volume_sma_20', 'volume_ratio_20']
X shape: (2685, 25)
y shape: (2685,)

In [14]:
from scipy.stats import f_oneway

anova_results = []

for feature in feature_cols:
    temp = pd.DataFrame({
        "feature": X[feature],
        "target": y
    }).dropna()

    # feature 값을 4개 분위수 그룹으로 분할
    temp["group"] = pd.qcut(
        temp["feature"],
        q=4,
        labels=False,
        duplicates="drop"
    )

    # 그룹별 target 추출
    groups = [
        group["target"].values
        for _, group in temp.groupby("group", observed=True)
    ]

    # 그룹이 2개 이상일 때만 ANOVA
    if len(groups) >= 2:
        f_stat, p_value = f_oneway(*groups)

        anova_results.append({
            "feature": feature,
            "f_statistic": f_stat,
            "p_value": p_value
        })

anova_df = pd.DataFrame(anova_results)

anova_df

             feature  f_statistic       p_value
0          return_1d     0.152699  9.279859e-01
1          return_5d     3.456288  1.580798e-02
2         return_10d     3.290291  1.984355e-02
3         return_20d     8.223861  1.905166e-05
4    intraday_return     0.440934  7.237445e-01
5     high_low_range     1.092316  3.510592e-01
6                gap     3.570503  1.351245e-02
7              sma_5     2.750267  4.130969e-02
8             sma_20     6.919353  1.225623e-04
9             sma_60     7.453631  5.725081e-05
10    price_to_sma_5     1.226294  2.985153e-01
11   price_to_sma_20     7.208524  8.119661e-05
12   price_to_sma_60     7.213298  8.064608e-05
13            rsi_14    13.411641  1.095335e-08
14            roc_10     3.290291  1.984355e-02
15            roc_20     8.223861  1.905166e-05
16              macd     7.435638  5.873912e-05
17       macd_signal     5.648773  7.423683e-04
18         macd_hist     7.460668  5.667901e-05
19      volatility_5     0.615655  6.048316e-01
20     volatility_20     0.962588  4.094178e-01
21            atr_14     4.129139  6.242946e-03
22  volume_change_1d     0.652891  5.811017e-01
23     volume_sma_20     3.327609  1.885613e-02
24   volume_ratio_20     4.299606  4.925685e-03

In [15]:
anova_df = anova_df.sort_values("p_value")

anova_df

             feature  f_statistic       p_value
13            rsi_14    13.411641  1.095335e-08
3         return_20d     8.223861  1.905166e-05
15            roc_20     8.223861  1.905166e-05
18         macd_hist     7.460668  5.667901e-05
9             sma_60     7.453631  5.725081e-05
16              macd     7.435638  5.873912e-05
12   price_to_sma_60     7.213298  8.064608e-05
11   price_to_sma_20     7.208524  8.119661e-05
8             sma_20     6.919353  1.225623e-04
17       macd_signal     5.648773  7.423683e-04
24   volume_ratio_20     4.299606  4.925685e-03
21            atr_14     4.129139  6.242946e-03
6                gap     3.570503  1.351245e-02
1          return_5d     3.456288  1.580798e-02
23     volume_sma_20     3.327609  1.885613e-02
14            roc_10     3.290291  1.984355e-02
2         return_10d     3.290291  1.984355e-02
7              sma_5     2.750267  4.130969e-02
10    price_to_sma_5     1.226294  2.985153e-01
5     high_low_range     1.092316  3.510592e-01
20     volatility_20     0.962588  4.094178e-01
22  volume_change_1d     0.652891  5.811017e-01
19      volatility_5     0.615655  6.048316e-01
4    intraday_return     0.440934  7.237445e-01
0          return_1d     0.152699  9.279859e-01

In [16]:
feature = "rsi_14"

temp = pd.DataFrame({
    "feature": X[feature],
    "target": y
}).dropna()

temp["group"] = pd.qcut(
    temp["feature"],
    q=4,
    labels=["Q1", "Q2", "Q3", "Q4"],
    duplicates="drop"
)

print(temp.groupby("group", observed=True)["target"].agg(["count", "mean", "std"]))

       count      mean       std
group
Q1       672  0.004422  0.062482
Q2       671  0.006213  0.070264
Q3       671  0.002763  0.069596
Q4       671  0.025905  0.098560

In [17]:
groups = [
    temp.loc[temp["group"] == group, "target"].values
    for group in ["Q1", "Q2", "Q3", "Q4"]
]

f_stat, p_value = f_oneway(*groups)

print("F-statistic:", f_stat)
print("p-value:", p_value)

F-statistic: 13.411640992325964
p-value: 1.0953347565675127e-08

In [18]:
temp.groupby("group", observed=True)["target"].mean()

group
Q1    0.004422
Q2    0.006213
Q3    0.002763
Q4    0.025905
Name: target, dtype: float64

In [ ]:
anova_df.to_csv(
    "../data/processed/filter_results/anova_target.csv",
    index=False
)

OSError: Cannot save file into a non-existent directory: '../../data/processed/filter_results'