In [9]:
import pandas as pd

rfe_rf = pd.read_csv("../../data/processed/filter_results/rfe_random_forest_results.csv")
rfe_xgb = pd.read_csv("../../data/processed/filter_results/rfe_xgboost_results.csv")
sfs_rf = pd.read_csv("../../data/processed/sfs_random_forest_performance.csv")
sfs_xgb = pd.read_csv("../../data/processed/sfs_xgboost_results.csv")

In [12]:
display(rfe_rf)
display(rfe_xgb)
display(sfs_rf)
display(sfs_xgb)

,method,n_features,step,n_estimators,max_depth,max_features,features,rmse
0,RFE + Random Forest,15,1.0,300,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050424
1,RFE + Random Forest,15,1.0,500,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050466
2,RFE + Random Forest,15,1.0,100,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050483
3,RFE + Random Forest,15,2.0,500,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050606
4,RFE + Random Forest,15,0.1,500,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050606
...,...,...,...,...,...,...,...,...
400,RFE + Random Forest,25,0.1,500,5.0,log2,"['return_1d', 'return_10d', 'return_20d', 'int...",0.057270
401,RFE + Random Forest,25,1.0,500,5.0,log2,"['return_1d', 'return_10d', 'return_20d', 'int...",0.057270
402,RFE + Random Forest,25,1.0,300,5.0,log2,"['return_1d', 'return_10d', 'return_20d', 'int...",0.057672
403,RFE + Random Forest,25,2.0,300,5.0,log2,"['return_1d', 'return_10d', 'return_20d', 'int...",0.057672
404,RFE + Random Forest,25,0.1,300,5.0,log2,"['return_1d', 'return_10d', 'return_20d', 'int...",0.057672

,n_features_to_select,rfe_step,selected_features,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,rmse,mae,r2
0,5,1.0,"sma_5,sma_60,macd_signal,volatility_20,atr_14",100,2,0.03,0.8,0.8,0.102682,0.076605,0.037854
1,5,1.0,"sma_5,sma_60,macd_signal,volatility_20,atr_14",100,2,0.03,0.8,1.0,0.102591,0.076478,0.039567
2,5,1.0,"sma_5,sma_60,macd_signal,volatility_20,atr_14",100,2,0.03,1.0,0.8,0.102741,0.076590,0.036746
3,5,1.0,"sma_5,sma_60,macd_signal,volatility_20,atr_14",100,2,0.03,1.0,1.0,0.102738,0.076464,0.036800
4,5,1.0,"sma_5,sma_60,macd_signal,volatility_20,atr_14",100,2,0.10,0.8,0.8,0.104840,0.078289,-0.003013
...,...,...,...,...,...,...,...,...,...,...,...
715,25,0.1,"return_1d,return_5d,return_10d,return_20d,intr...",500,5,0.03,1.0,1.0,0.110335,0.083569,-0.110913
716,25,0.1,"return_1d,return_5d,return_10d,return_20d,intr...",500,5,0.10,0.8,0.8,0.112829,0.085884,-0.161698
717,25,0.1,"return_1d,return_5d,return_10d,return_20d,intr...",500,5,0.10,0.8,1.0,0.114546,0.086669,-0.197328
718,25,0.1,"return_1d,return_5d,return_10d,return_20d,intr...",500,5,0.10,1.0,0.8,0.110779,0.083478,-0.119864
719,25,0.1,"return_1d,return_5d,return_10d,return_20d,intr...",500,5,0.10,1.0,1.0,0.111409,0.084522,-0.132646

,n_features_to_select,tol,n_selected_features,MSE,RMSE,MAE,R2
0,5,0.000,5,0.002336,0.048336,0.033952,0.606246
1,5,0.001,5,0.002336,0.048336,0.033952,0.606246
2,5,0.005,5,0.002336,0.048336,0.033952,0.606246
3,10,0.000,10,0.002203,0.046939,0.032997,0.627828
4,10,0.001,10,0.002203,0.046939,0.032997,0.627828
5,10,0.005,10,0.002203,0.046939,0.032997,0.627828
6,15,0.000,15,0.002433,0.049327,0.034789,0.588933
7,15,0.001,15,0.002433,0.049327,0.034789,0.588933
8,15,0.005,15,0.002433,0.049327,0.034789,0.588933
9,20,0.000,20,0.002723,0.052179,0.037013,0.540898
10,20,0.001,20,0.002723,0.052179,0.037013,0.540898
11,20,0.005,20,0.002723,0.052179,0.037013,0.540898

,n_features_to_select,tol,n_selected_features,selected_features
0,5,0.000,5,"['sma_5', 'sma_60', 'price_to_sma_60', 'volati..."
1,5,0.001,5,"['sma_5', 'sma_60', 'price_to_sma_60', 'volati..."
2,5,0.005,5,"['sma_5', 'sma_60', 'price_to_sma_60', 'volati..."
3,10,0.000,10,"['sma_5', 'sma_20', 'sma_60', 'price_to_sma_60..."
4,10,0.001,10,"['sma_5', 'sma_20', 'sma_60', 'price_to_sma_60..."
5,10,0.005,10,"['sma_5', 'sma_20', 'sma_60', 'price_to_sma_60..."
6,15,0.000,15,"['return_10d', 'return_20d', 'sma_5', 'sma_20'..."
7,15,0.001,15,"['return_10d', 'return_20d', 'sma_5', 'sma_20'..."
8,15,0.005,15,"['return_10d', 'return_20d', 'sma_5', 'sma_20'..."
9,20,0.000,20,"['return_5d', 'return_10d', 'return_20d', 'hig..."
10,20,0.001,20,"['return_5d', 'return_10d', 'return_20d', 'hig..."
11,20,0.005,20,"['return_5d', 'return_10d', 'return_20d', 'hig..."

In [13]:
print("RFE + RF")
print(rfe_rf.shape)

print("\nRFE + XGBoost")
print(rfe_xgb.shape)

print("\nSFS + RF")
print(sfs_rf.shape)

print("\nSFS + XGBoost")
print(sfs_xgb.shape)

RFE + RF
(405, 8)

RFE + XGBoost
(720, 11)

SFS + RF
(12, 7)

SFS + XGBoost
(12, 4)

In [15]:
print(rfe_rf.iloc[0])
print()

method                                        RFE + Random Forest
n_features                                                     15
step                                                          1.0
n_estimators                                                  300
max_depth                                                    10.0
max_features                                                  0.5
features        ['return_1d', 'return_10d', 'return_20d', 'int...
rmse                                                     0.050424
Name: 0, dtype: object

In [16]:
print(rfe_xgb.iloc[0])
print()

n_features_to_select                                                5
rfe_step                                                          1.0
selected_features       sma_5,sma_60,macd_signal,volatility_20,atr_14
n_estimators                                                      100
max_depth                                                           2
learning_rate                                                    0.03
subsample                                                         0.8
colsample_bytree                                                  0.8
rmse                                                         0.102682
mae                                                          0.076605
r2                                                           0.037854
Name: 0, dtype: object

In [17]:
print(sfs_rf.iloc[0])
print()

n_features_to_select    5.000000
tol                     0.000000
n_selected_features     5.000000
MSE                     0.002336
RMSE                    0.048336
MAE                     0.033952
R2                      0.606246
Name: 0, dtype: float64

In [18]:
print(sfs_xgb.iloc[0])
print()

n_features_to_select                                                    5
tol                                                                   0.0
n_selected_features                                                     5
selected_features       ['sma_5', 'sma_60', 'price_to_sma_60', 'volati...
Name: 0, dtype: object

In [21]:
import pandas as pd
import ast

rfe_rf = pd.read_csv("../../data/processed/filter_results/rfe_random_forest_results.csv")
rfe_xgb = pd.read_csv("../../data/processed/filter_results/rfe_xgboost_results.csv")

sfs_rf = pd.read_csv("../../data/processed/sfs_random_forest_performance.csv")
sfs_rf_features = pd.read_csv("../../data/processed/sfs_random_forest_feature_sets.csv")

sfs_xgb = pd.read_csv("../../data/processed/sfs_xgboost_results.csv")

print("RFE + RF:", rfe_rf.shape)
print("RFE + XGBoost:", rfe_xgb.shape)
print("SFS + RF:", sfs_rf.shape)
print("SFS + RF feature sets:", sfs_rf_features.shape)
print("SFS + XGBoost:", sfs_xgb.shape)

RFE + RF: (405, 8)
RFE + XGBoost: (721, 1)
SFS + RF: (12, 7)
SFS + RF feature sets: (12, 4)
SFS + XGBoost: (12, 4)

In [22]:
print("RFE + RF")
display(rfe_rf.head())

print("RFE + XGBoost")
display(rfe_xgb.head())

print("SFS + RF")
display(sfs_rf.head())

print("SFS + RF feature sets")
display(sfs_rf_features.head())

print("SFS + XGBoost")
display(sfs_xgb.head())

RFE + RF

,method,n_features,step,n_estimators,max_depth,max_features,features,rmse
0,RFE + Random Forest,15,1.0,300,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050424
1,RFE + Random Forest,15,1.0,500,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050466
2,RFE + Random Forest,15,1.0,100,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050483
3,RFE + Random Forest,15,2.0,500,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050606
4,RFE + Random Forest,15,0.1,500,10.0,0.5,"['return_1d', 'return_10d', 'return_20d', 'int...",0.050606

RFE + XGBoost

                                                                                                                                                                                             #R^2 기준 내림차순
n_features_to_select rfe_step selected_features                             n_estimators max_depth learning_rate subsample colsample_bytree rmse                mae                                    r2
5                    1.0      sma_5,sma_60,macd_signal,volatility_20,atr_14 100          2         0.03          0.8       0.8              0.10268217535733401 0.07660464808852391   0.03785425335231618
                                                                                                                           1.0              0.10259076230420042 0.07647773967035007  0.039566595926131765
                                                                                                                 1.0       0.8              0.10274129292199514 0.07658954358667763  0.036746055420783685
                                                                                                                           1.0              0.10273839986704297 0.0764639701974609   0.036800302496711956

SFS + RF

,n_features_to_select,tol,n_selected_features,MSE,RMSE,MAE,R2
0,5,0.000,5,0.002336,0.048336,0.033952,0.606246
1,5,0.001,5,0.002336,0.048336,0.033952,0.606246
2,5,0.005,5,0.002336,0.048336,0.033952,0.606246
3,10,0.000,10,0.002203,0.046939,0.032997,0.627828
4,10,0.001,10,0.002203,0.046939,0.032997,0.627828

SFS + RF feature sets

,n_features_to_select,tol,n_selected_features,selected_features
0,5,0.000,5,"sma_60,price_to_sma_60,macd_signal,volatility_..."
1,5,0.001,5,"sma_60,price_to_sma_60,macd_signal,volatility_..."
2,5,0.005,5,"sma_60,price_to_sma_60,macd_signal,volatility_..."
3,10,0.000,10,"sma_5,sma_20,sma_60,price_to_sma_60,macd,macd_..."
4,10,0.001,10,"sma_5,sma_20,sma_60,price_to_sma_60,macd,macd_..."

SFS + XGBoost

,n_features_to_select,tol,n_selected_features,selected_features
0,5,0.000,5,"['sma_5', 'sma_60', 'price_to_sma_60', 'volati..."
1,5,0.001,5,"['sma_5', 'sma_60', 'price_to_sma_60', 'volati..."
2,5,0.005,5,"['sma_5', 'sma_60', 'price_to_sma_60', 'volati..."
3,10,0.000,10,"['sma_5', 'sma_20', 'sma_60', 'price_to_sma_60..."
4,10,0.001,10,"['sma_5', 'sma_20', 'sma_60', 'price_to_sma_60..."

In [37]:
best_rfe_rf = rfe_rf.loc[rfe_rf["rmse"].idxmin()]

best_rfe_xgb = rfe_xgb_results.loc[
    rfe_xgb_results["rmse"].idxmin()
]

best_sfs_rf = sfs_rf.loc[sfs_rf["RMSE"].idxmin()]

print("===== Best Performance =====")

print("\nRFE + Random Forest")
print(best_rfe_rf)

print("\nRFE + XGBoost")
print(best_rfe_xgb)

print("\nSFS + Random Forest")
print(best_sfs_rf)

===== Best Performance =====

RFE + Random Forest
method                                        RFE + Random Forest
n_features                                                     15
step                                                          1.0
n_estimators                                                  300
max_depth                                                    10.0
max_features                                                  0.5
features        ['return_1d', 'return_10d', 'return_20d', 'int...
rmse                                                     0.050424
Name: 0, dtype: object

RFE + XGBoost
n_features_to_select                                                  5
rfe_step                                                            0.1
selected_features       sma_5,sma_60,volatility_20,atr_14,volume_sma_20
n_estimators                                                        100
max_depth                                                             2
learning_rate                                                      0.03
subsample                                                           1.0
colsample_bytree                                                    1.0
rmse                                                           0.100622
mae                                                            0.074809
r2                                                             0.076078
Name: 75, dtype: object

SFS + Random Forest
n_features_to_select    10.000000
tol                      0.000000
n_selected_features     10.000000
MSE                      0.002203
RMSE                     0.046939
MAE                      0.032997
R2                       0.627828
Name: 3, dtype: float64

In [34]:
import pandas as pd

rfe_xgb_results = pd.read_csv(
    "../../data/processed/filter_results/rfe_xgboost_results.csv",

)

print(rfe_xgb_results.shape)
print(rfe_xgb_results.columns.tolist())

(720, 11)
['n_features_to_select', 'rfe_step', 'selected_features', 'n_estimators', 'max_depth', 'learning_rate', 'subsample', 'colsample_bytree', 'rmse', 'mae', 'r2']

In [35]:
print(rfe_xgb_results["rmse"].head())
print(rfe_xgb_results["rmse"].dtype)

0    0.102682
1    0.102591
2    0.102741
3    0.102738
4    0.104840
Name: rmse, dtype: float64
float64

In [36]:
best_rfe_xgb = rfe_xgb_results.loc[
    rfe_xgb_results["rmse"].idxmin()
]

display(best_rfe_xgb)

n_features_to_select                                                  5
rfe_step                                                            0.1
selected_features       sma_5,sma_60,volatility_20,atr_14,volume_sma_20
n_estimators                                                        100
max_depth                                                             2
learning_rate                                                      0.03
subsample                                                           1.0
colsample_bytree                                                    1.0
rmse                                                           0.100622
mae                                                            0.074809
r2                                                             0.076078
Name: 75, dtype: object